### ISSUE TITLE
Another issue with a board

### ISSUE THREAD

**Issue by dnlhtz** [gebruederheitz/board-demo#2]
https://app.leanboard.io/board/b15ecb37-6625-4673-8d16-2d2ed830fe49
![LeanBoard](https://app.leanboard.io/api/board/b15ecb37-6625-4673-8d16-2d2ed830fe49/image.png)

**Comment by AlisaNikia** [comment]
Scheint nicht mehr relevant zu sein und wird deshalb geschlossen.
